# Generated by Django 5.1.5 on 2025-03-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productModel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomeUser',
        ),
    ]
