# Generated by Django 5.1.5 on 2025-03-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverBase', '0004_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='userName',
            new_name='user',
        ),
    ]
